### ISSUE TITLE
How slow would the uart version need to be for it to be able to feedback too

### ISSUE THREAD

**Issue by ukscone** [envenomator/agon-hexload#2]
not a big fan of patched VDPs (other than messing around temporarily) so curious how slow we'd need the UART to be for it to give feedback of the transfer a la patched VDP transfer.  personally i think even 2400 or 9600 would be acceptable for the file sizes we are dealing with

**Comment by envenomator** [comment]
That would require an overhaul of the code to the UART, to test acceptability. Transfer speeds would indeed be an order of magnitude lower, or it would require DTS/DSR to the client, which not everyone would be able to achieve with their choice of serial interface.
