### ISSUE TITLE
Errors on transfer

### ISSUE THREAD

**Issue by paulscottrobson** [envenomator/agon-hexload#4]
Had to reduce the speed to 76800 to get a reliable transfer. Is it worth considering an alternate encoding, packing 6 bits/byte rather than <4 ?
(Olimex board version)

**Comment by envenomator** [comment]
I get a sustained 384Kbit/s

**Comment by envenomator** [comment]
How would you propose to use 6bits/byte using the intel ihex format? It seems that this would change the nature of the tool completely

**Comment by paulscottrobson** [comment]
Weird. I've tinkered with it all ways and at 115200 baud I get errors in about every 20-30 packets, At 76800 it seems flawless. I've noticed others have the same problem. 

I'd probably pack 3 bytes into 4 characters mapping them onto (say) 48..111
