### ISSUE TITLE
Test Hex File

### ISSUE THREAD

**Issue by paulscottrobson** [envenomator/agon-hexload#5]
[testprogram.zip](https://github.com/envenomator/agon-hexload/files/12102504/testprogram.zip)

I found when testing it helped to have a hex file that definitely worked when getting this running. Attached is a simple one.

**Comment by envenomator** [comment]
I have been using bbcbasic, freshly compiled to .hex format with 35KB thus far.

**Comment by envenomator** [comment]
I've just blasted over 35KB over bbcbasic.hex with two different ftdi adapters using Win10 / 384.000 baud. No errors

**Comment by envenomator** [comment]
With two different Agon boards; the Agon original and the Agon light2.

**Comment by envenomator** [comment]
![20230720_080005659_iOS](https://github.com/envenomator/agon-hexload/assets/47718809/4f9fd590-44ad-49fa-bbc3-d709f1082b76)

**Comment by envenomator** [comment]
![20230720_082456904_iOS](https://github.com/envenomator/agon-hexload/assets/47718809/190a61b7-2783-4af4-b2c9-b89c4848d348)
And to remove all doubt regarding programs that definitely worked, or the speed I'm getting

**Comment by james7780** [comment]
FWIW, I upload 170kb .bin at 230400 baud/bps with my cheap FTDI adapter connected using very dodgy jumper wires. 384000 results in errors too often. I suggest that Paul check his cabling and connections, and make sure the FTDI apadter is set to 3.3V (and/or try a different FTDI adapter?).

**Comment by envenomator** [comment]
Slower than expected serial-over-USB speeds have also been reported in programming the VDP, using the Arduino IDE or platformIO. It seems like there is some significant variation in what platforms (Mac/Linux/Windows, USB 1.0/2.0/3.0, with or without Hub) are able to achieve reliably using async serial protocol. This isn't something I'm striving to solve with this tool. It would be prudent to start with a much lower serial speed generally, say potentially as low as 57600 and then let each user experience how much faster they are able to get. Or slower even.

For example, 512Kbaud is asking too much from my setup, even though I'm using a dedicated USB3.0 port with a modern non-cloned USB-serial IC on an FTDI board, without hub. At certain speeds, even the OS driver comes into play.

**Comment by envenomator** [comment]
To put things into perspective, there have also been some demands/requests for additional feedback during the uart transmission, which would have required the speed to significantly drop to handle the overhead of transmitting to the FTDI side during reception. Some people where willing for the tool to then even go to 9.600 baud, just to have this reporting feature in. 
I was not willing to do that, but it goes to show that speed is objective.

**Comment by envenomator** [comment]
And lastly, async serial could technically be made robust, requiring hardware handshakes during transmission. Then we would gain real speed-up and let the slowest link in the chain be responsible for the effective end-to-end speed. Unfortunately, this will immediately rule out a significant portion of FDTI adapters in the field, not to mention support from specific serial software or APIs. The common denominator is async serial without handshakes, resulting in speeds that may vary wildly between setups.
It appears that the Agon variant currently can easily, reliably, reach 384Kbaud. Mileage with other peoples setup may vary.
